### PR TITLE
Autoloading classes inside includes folder

### PR DESCRIPTION
**Pull request by gpressutto5**

### CODE REVIEW

**Comment by gpressutto5** [comment]
Just to remember later: This pull request won't work with Boleto payments.

**Comment by cezarlz** [comment]
@gpressutto5 What is the reason?

**Comment by gpressutto5** [comment]
@cezarlz idk, but I think it has something to do with the lack of a `includes()` method

**Comment by SparK-Cruz** [comment]
After a restructure of our folders this one will be obsolete... so, closing.

**Pull request closed without merging**
