### PR TITLE
use getters instead of accessing properties directly

### PR DESCRIPTION
**Pull request by romuloctba**
This should avoid notices like

```
Notice: id foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/______/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, call_user_func, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_received, wc_get_template, include('/themes/_________/woocommerce/checkout/thankyou.php'), do_action('woocommerce_thankyou'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, woocommerce_order_details_table, wc_get_template, include('/plugins/woocommerce/templates/order/order-details.php'), do_action('woocommerce_order_details_after_order_table_items'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_EBANX_My_Account->order_details, WC_EBANX_Banking_Ticket_Gatewa in wp-includes/functions.php on line 4161
```

Please regression test this completely before mergeing

### CODE REVIEW

**Comment by romuloctba** [comment]
Sorry, Travis ☹️
I'll try to make him happy later today

**Comment by romuloctba** [comment]
I think this  build attempt was unsuccessful due some system unavailability, am I right?

```
....
waiting for woocommerce-container
The job exceeded the maximum time limit for jobs, and has been terminated.
```


how do I ask it to run again? (without making a dummy commit)

**Comment by romuloctba** [comment]
oh i know, ill reopen this pr

**Comment by romuloctba** [comment]
Any guidance on this?

**Comment by romuloctba** [comment]
This might be related to some misuse of the globals that loads the order in a wrong way at woocommerce-gateway-ebanx.php , thus making ->get_id() call invalid.

Needs further investigation

I mean, if anyone even care

**Comment by andercampanha** [comment]
Unfortunately we cannot merge this PR the way it is because it would break compatibility with WooCommerce 2.x and people might still be using it. We will take a look at this and fix it assuring compatibility shortly. Until then, keeping the debugger off for production environment should make those harmless notes invisible.

**Pull request closed without merging**
